image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - image-build
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

image-build:
  stage: image-build
  script:
    - mvn $MAVEN_CLI_OPTS -P jib compile jib:build

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
    - kubectl apply -f k8s/deployment.yaml